### ISSUE TITLE
Revert back to previous deployment so I can keep tracking the GA and Freshchat

### ISSUE THREAD

**Issue by faultables** [evilfactorylabs/web#21]
I cannot access the Freshchat popup message, help. Ok this is Sunday but I am working everyday

![Screen Shot 2019-07-14 at 18 58 21](https://user-images.githubusercontent.com/6561394/61183271-7c60b400-a669-11e9-9555-f53cea090008.png)

**Comment by anakmagang** [comment]
wontfix
